export * from './ApiResult'

export * from './Address'
export * from './AddressResult'
export * from './SpotTime'
export * from './Stop'
export * from './Trip'
export * from './Vehicle'
export * from './PaymentMethod'
export * from './PaymentType'
export * from './Place'
export * from './User'
