import { Action, Module, VuexModule } from 'vuex-class-modules'
import { Route, Location } from 'vue-router/types/router'
@Module({ generateMutationSetters: true })
class AppModule extends VuexModule {
  // state
  appTitle = 'CharterUP for Operators'
  lastRoute: Location | null = null

  // getters
  get getAppTitle() {
    return this.appTitle
  }

  get getLastRoute() {
    return this.lastRoute
  }

  // mutations (mutations are autogenerated for each root level state field)

  // actions
  @Action
  saveLastRoute(route: Route): void {
    this.lastRoute = {
      name: route?.name || undefined,
      path: route?.path,
      hash: route?.hash,
      query: route?.query,
      params: route?.params,
    }
  }
}

// register module (could be in any file)
import store from '@/store/index'
export default new AppModule({ store, name: 'app' })