import { Action, Module, VuexModule } from 'vuex-class-modules'

@Module({ generateMutationSetters: true })
class AppModule extends VuexModule {
  // state
  appTitle = 'Vue2 TS Boilerplate'

  // getters
  get getAppTitle() {
    return this.appTitle
  }

  // mutations (mutations are autogenerated for each root level state field)

  // actions
}

// PRIVATE HELPERS

// register module (could be in any file)
import store from '@/store/index'
export default new AppModule({ store, name: 'app' })
