import { VuexModule, Module, Action } from 'vuex-class-modules'
import axios from 'axios'

import auth from '@/services/auth'
import router from '@/router'

import { UserAuthPayload, Role } from '@/models/dto'
import { save, load } from '@/utils/localStorage'

@Module({ generateMutationSetters: true })
class AuthModule extends VuexModule {
  // state
  user = {}
  token: string | null = load('token') || null
  isTokenSet = !!load('token')
  roles: Role[] = []

  // getters
  get getUser() {
    return this.user
  }
  get getToken() {
    return this.token
  }
  get getIsTokenSet() {
    return this.isTokenSet
  }
  get getRoles() {
    return this.roles
  }

  // mutations (mutations are autogenerated for each root level state field)

  // actions
  @Action
  async login(payload: UserAuthPayload) {
    const response = await auth.login(payload)
    if (response.data.successful) {
      save('user', response.data.user)
      save('token', response.data.token)
      this.user = response.data.user
      this.token = response.data.token
      this.isTokenSet = true
      registerBearerToken(response.data.token)
    }
  }

  @Action
  autoLogin() {
    this.user = load('user')
    this.token = load('token')
    this.isTokenSet = true
    if (this.token) {
      registerBearerToken(this.token)
    }
  }

  @Action
  async logout() {
    window.localStorage.removeItem('token')
    window.localStorage.removeItem('user')
    window.localStorage.removeItem('roles')
    this.isTokenSet = false
    router.push({
      name: 'login',
    })
  }

  @Action
  async getUserProfile() {
    const response = await auth.getUserProfile()
    if (response.data.successful) {
      save('roles', response.data.userProfile.roles)
      this.roles = response.data.userProfile.roles
    }
  }
}

//private helpers
function registerBearerToken(token: string): void {
  axios.defaults.headers.common['Authorization'] = `Bearer ${token}`
}
// register module
import store from '@/store/index'
export default new AuthModule({ store, name: 'auth' })
