import { VuexModule, Module, Action } from 'vuex-class-modules'
import axios from 'axios'

import auth from '@/services/auth'
import user from '@/services/user'
import router from '@/router'

import { UserAuthPayload, UserDetail, Role } from '@/models/dto'
import { save, load } from '@/utils/localStorage'

@Module({ generateMutationSetters: true })
class AuthModule extends VuexModule {
  // state
  userId: number | null = load('userId') || null
  user: UserDetail | null = load('user') || null
  token: string | null = load('token') || null
  isTokenSet = !!load('token')
  roles: Role[] = load('roles') || []
  isDriverOnly = false

  // getters
  get getUser() {
    return this.user
  }
  get getUserId() {
    return this.userId
  }
  get getToken() {
    return this.token
  }
  get getIsTokenSet() {
    return this.isTokenSet
  }
  get getRoles() {
    return this.roles
  }
  get getFullName() {
    return `${this.user.firstName} ${this.user.lastName}`
  }
  get getIsDriverOnly() {
    return this.isDriverOnly
  }

  // mutations (mutations are autogenerated for each root level state field)

  // actions
  @Action
  async login(payload: UserAuthPayload) {
    const response = await auth.login(payload)
    if (response.data.successful) {
      save('userId', response.data.user.userId)
      save('token', response.data.token)
      this.token = response.data.token
      this.user = response.data.user
      this.userId = response.data.user.userId
      this.isTokenSet = true
      registerBearerToken(response.data.token)
    }
  }

  @Action
  autoLogin() {
    this.user = load('user')
    this.token = load('token')
    this.isTokenSet = true
    if (this.token) {
      registerBearerToken(this.token)
    }
  }

  @Action
  async logout() {
    window.localStorage.removeItem('token')
    window.localStorage.removeItem('user')
    window.localStorage.removeItem('userId')
    window.localStorage.removeItem('roles')
    this.userId = null
    this.user = null
    this.token = null
    this.roles = null
    this.isTokenSet = false
    router.push({
      name: 'login',
    })
  }

  @Action
  async getUserProfile() {
    const response = await auth.getUserProfile()
    if (response.data.successful) {
      save('roles', response.data.userProfile.roles)
      this.roles = response.data.userProfile.roles
      this.isDriverOnly = checkIsDriverOnly(response.data.userProfile.roles)
    }
  }

  @Action
  async getUserDetail() {
    if (!this.userId) {
      return
    }

    const response = await user.byId(this.userId)
    // Seems like we don't have a `successful` property to check on this response?
    if (response.status === 200) {
      this.user = response.data
      save('user', response.data)
    }
  }
}

//private helpers
const registerBearerToken = (token: string): void => {
  axios.defaults.headers.common['Authorization'] = `Bearer ${token}`
}

const checkIsDriverOnly = (roles: Role[]): boolean => {
  if (roles && roles.length) {
    const isDriver = roles.some((role) => role.roleName === 'is_driver')
    const isAdmin = roles.some((role) =>
      [
        'is_free_admin',
        'is_paid_admin',
        'is_broker_admin',
        'is_admin_admin',
      ].includes(role.roleName)
    )
    const isUser = roles.some((role) =>
      [
        'is_free_user',
        'is_paid_user',
        'is_broker_user',
        'is_report_admin',
      ].includes(role.roleName)
    )
    return !isAdmin && !isUser && isDriver
  }
  return false
}

// register module
import store from '@/store/index'
export default new AuthModule({ store, name: 'auth' })
