import { VuexModule, Module, Action } from 'vuex-class-modules'

@Module({ generateMutationSetters: true })
class SidebarModule extends VuexModule {
  // state
  sidebarOpen = false

  // getters
  get isOpen(): boolean {
    return this.sidebarOpen
  }

  // mutations (mutations are autogenerated for each root level state field)

  // actions
  @Action
  open() {
    this.sidebarOpen = true
  }

  @Action
  close() {
    this.sidebarOpen = false
  }
}

// register module (could be in any file)
import store from '@/store/index'
export default new SidebarModule({ store, name: 'sidebar' })
